### ISSUE TITLE
Better YM2608 emulation core?

### ISSUE THREAD

**Issue by freq-mod** [gzaffin/pmdmini#11]
Hello,
This player uses pmdwin, which accuracy falls apart when playing PMD songs that use SSG-EG : [TH13_01.M2.tar.gz](https://github.com/gzaffin/pmdmini/files/5894882/TH13_01.M2.tar.gz)
Is it possible to replace emulation engine with one from MAME, or maybe even [this](https://github.com/rerrahkr/BambooTracker/tree/master/BambooTracker/chip/nuked)?

EDIT: [ssgeg.tar.gz](https://github.com/gzaffin/pmdmini/files/5895299/ssgeg.tar.gz) more proper example, lead instrument is very noisy due to incorrect emulation

**Comment by freq-mod** [comment]
As of now, FMPMD2000 (and PMDWin.dll) got upgraded to use BSD-licenced MAME core https://github.com/aaronsgiles/ymfm

**Comment by gzaffin** [comment]
A dedicated branch `PMDWinS051` is created for importing c60 PMDWin ver. 051 which uses ymfm.
I tested on Windows, please have a look at it.
I'm going to test on Linux, at least Lubuntu distribution, since I have an old laptop with that o.s.

**Comment by freq-mod** [comment]
managed to find some time to test it - SSG-EG is properly emulated, however I noticed the same bug as in FMPMD2000 - RSS cymbal sample is played at an improper pitch. I don't know if it is the problem with PMDWin or MAME emulation, though...

**Comment by gzaffin** [comment]
Regarding OPNA Rhythm Sound Source I can say that these days I found different versions of wav packages, I mentioned in «How to use pmdplay player» section of README.md of added branches, You can try all of them if they perform better, even though I think ymfm uses 8 kBytes ADPCM-A `ym2608_adpcm_rom.bin` binary rom image, I'm not sure about this. You can also test with the other branch `PMDWinS041`.

**Comment by freq-mod** [comment]
I see, with ym2608 rom binary, it sounds correct, thanks

**Comment by freq-mod** [comment]
Can S051 branch be merged? Or still something to finish?

**Comment by gzaffin** [comment]
Do You mean merge with master? I think so. I've got no activities to do but bug-fixes if there are any.
