### ISSUE TITLE
Can't use RSS samples

### ISSUE THREAD

**Issue by OPNA2608** [gzaffin/pmdmini#12]
I'm unable to hear the RSS samples no matter what I try. Checking the source code would indicate to me that i should put them in `$HOME/.pmdplay/`
https://github.com/gzaffin/pmdmini/blob/0ebd41c6d5cb4fd3537e839afdbed9f41a015bec/sdlplay.cpp#L371-L384
but strace'ing pmdplay shows that the only path it tries to load the samples from is `./`.
![grafik](https://user-images.githubusercontent.com/23431373/106307842-227e0a00-6260-11eb-85be-5d59669010eb.png)
Putting those samples into `$HOME/.pmdplay/` doesn't seem to do anything. Using `$PWD` instead and running strace again, it looks like they are found properly, but there's still no RSS samples in the audible output.
![grafik](https://user-images.githubusercontent.com/23431373/106308079-7d176600-6260-11eb-8de4-0d9356dd9009.png)

**Comment by gzaffin** [comment]
Now $(HOME)/.pmdplay/ is where .WAV files in all capitol letters should be put.
See [NEKO PROJECT 2 home page](http://fullmotionvideo.free.fr/pc98/neko.html).
Direct link to roms.zip [here](http://fullmotionvideo.free.fr/pc98/roms.zip), I used a capitalize version of .WAV files.
`
    char buf[1024];
    char *pcmdir = std::getenv( "HOME" );

    if (pcmdir)
    {
        std::strcpy(buf,pcmdir);
        strcat(buf,"/.pmdplay/");
    }
    else
    {
        buf[0] = 0;
    }

    pmd_init( buf );
`

**Comment by freq-mod** [comment]
For some reason, still I can't hear RSS samples. .WAVs were put into /home/USERNAME/.pmdplay, yet song is playing without them.

**Comment by OPNA2608** [comment]
Doesn't work for me either. I see it's reading the samples from ~/.pmdplay now but they're still not getting played back. The same samples play fine in FMPMD2000.

![grafik](https://user-images.githubusercontent.com/23431373/108045310-9cc1d300-7043-11eb-9fa6-17852800ea38.png)

[Th02_02.wav.zip](https://github.com/gzaffin/pmdmini/files/5987593/Th02_02.wav.zip)

**Comment by gzaffin** [comment]
I have to work on it some more hours.

**Comment by gzaffin** [comment]
Please try it again after sunday commits.

**Comment by freq-mod** [comment]
After cff7251, can confirm RSS is finally audible!
