### ISSUE TITLE
PPS format sample playback is broken

### ISSUE THREAD

**Issue by freq-mod** [gzaffin/pmdmini#13]
[pps.tar.gz](https://github.com/gzaffin/pmdmini/files/5895564/pps.tar.gz) - songs that use PPS samples don't play them, instead standard SSG percussion is used

**Comment by freq-mod** [comment]
I'm sorry, but I still hear that SSGPCM is played back correctly, falling back to standard SSG precussion :thinking:

**Comment by gzaffin** [comment]
Do not be sorry.
Do You want both .PPS files to be loaded even though CLEAR.M2 does not refers to them?
How is it supposed to work?

**Comment by freq-mod** [comment]
>Do You want both .PPS files to be loaded even though CLEAR.M2 does not refers to them?

Weird, it should refer to at least DRUMS.PPS...
[tmix98.zip](https://github.com/gzaffin/pmdmini/files/5978182/tmix98.zip) - can you please check any of these files?

**Comment by gzaffin** [comment]
in tmix98.zip, CLEAR.M and CLEAR.M2 use PPS02.PPS as per FMPPMD2000 Parameter Viewer ... I switched to Windows again

**Comment by freq-mod** [comment]
yeah, I included that bank in previous comment. Under FMPMD2000 it plays as it should, under pmdplay and 98fmplayer - not so much

**Comment by gzaffin** [comment]
I will continue on next weekends...

**Comment by gzaffin** [comment]
Please try it again after sunday commits.

**Comment by freq-mod** [comment]
Now it works as intended, thanks!
