### ISSUE TITLE
PCMMusDriver.h and pcmmusdriver.h filename clash

### ISSUE THREAD

**Issue by OPNA2608** [gzaffin/pmdmini#14]
On case-insensitive filesystems, `PCMMusDriver.h` and `pcmmusdriver.h` can cause some weirdness.

I'm fetching this repository on Linux & macOS and running a checksum against the contents to verify its integrity. macOS, being case-insensitive seems to give me a different hash than Linux, which is case-sensitive. This will make packaging & subsequent updating without a macOS system a pain for me.

Could one of them be removed or are both of them required? They have the same contents and only the lowercase version seems to be explicitly `#include`d.

**Comment by gzaffin** [comment]
I removed PCMMusDriver.h file.
