### ISSUE TITLE
[Enhacement] Ability to play looping songs continously

### ISSUE THREAD

**Issue by freq-mod** [gzaffin/pmdmini#15]
Currently it's not possible, songs are played only once.

**Comment by gzaffin** [comment]
I think this enhancement is done.
pmdplay now parses up to four arguments and fourth is repetition.
Repetition value is 0 <= repetition <= 99 with 0 meaning repeat loop part/song forever.

**Comment by freq-mod** [comment]
I don't understand someting. Let's say I just want to play a track, without WAV output, that loops continuously. How to do it?

`pmdplay file.m2 repetitions=0`doesn't work

**Comment by gzaffin** [comment]
Ok, use double dash to fill uninteresting arguments.
$ pmdplay file.m2 -- -- 0
is the way to play file.m2 forever.
$ pmdplay file.m2 -- -- 3
is the way to play file.m2 a first time plus 2 other times loop part or the entire song if pmd file has not a loop part.
