### ISSUE TITLE
Certain PMD song doesn't play on pmdplay

### ISSUE THREAD

**Issue by freq-mod** [gzaffin/pmdmini#17]
[FMTEST2.zip](https://github.com/gzaffin/pmdmini/files/6411271/FMTEST2.zip) - trying to play it exits the program immediately, with only `PMDPLAY on SDL Version 2011-10-21` message showing up. The same song works on 98fmplayer and, supposedly, on FMPMD2000.

EDIT: seems to have something related to SSG volume: "there is a bug with PMD allows you to set >15 for SSG volume"

**Comment by gzaffin** [comment]
@freq-mod This defect is caused to a consistency check: it skips playing modules if play time is less than a second. Would You prefer pmdplay play with a fixed repetition number? Would You prefer pmdplay to loop it forever?

**Comment by freq-mod** [comment]
>Would You prefer pmdplay to loop it forever?

The second option

>P.S. It seems to me both modules play just a chaotic noise.

It's supposed to be like that. It's interesting - it's a test of how low FM chips can go in pitch, below o1c.

**Comment by freq-mod** [comment]
thanks, now it plays!
