### ISSUE TITLE
pmdplay ignores Ctrl+C

### ISSUE THREAD

**Issue by OPNA2608** [gzaffin/pmdmini#20]
Once started, a song cannot be stopped prematurely. This is particularly unfortunate when infinite looping is being used. `SIGKILL` has to be sent to the process from a different terminal (`SIGTERM` is also ignored). SDL version 2.24.2.

https://user-images.githubusercontent.com/23431373/202048712-bcb413c3-3755-4c90-b265-f3e0d82d1b7b.mp4

**Comment by gzaffin** [comment]
Code changes for managing Ctrl-C are on two branches, not in main branch that I don't use.

**Comment by gzaffin** [comment]
I'm about to close this issue, anything against me doing it?
