### ISSUE TITLE
issue with 64 bits / easy fix

### ISSUE THREAD

**Issue by yoyofr** [gzaffin/pmdmini#21]
Hello,

I'm using pmdmini in Modizer and I've identified an issue with 64bits env, leading to crash for MZ file using PZI sample file. The DWORD definition needs to be updated to "unsigned int" instead of "unsigned long" , in types.h & pcmmusdriver.h.

**Comment by gzaffin** [comment]
Hi yoyofr,
can You please suggest me a failing test case, some failing test cases, to test a possible fix against?
Thanks,
Giangiacomo

**Comment by yoyofr** [comment]
sure, please try with attached files
[Actraiser.zip](https://github.com/gzaffin/pmdmini/files/15185121/Actraiser.zip)

**Comment by yoyofr** [comment]
Forget it, I was using an older version. With current one there's no issue anymore :)
