### ISSUE TITLE
Bad handling of missing PPC/PVI banks

### ISSUE THREAD

**Issue by OPNA2608** [gzaffin/pmdmini#8]
If a required P86 banks fails to be found, an attempt is made to find "P86" in the filename, replace it with "PPC" and look for a fallback PPC bank instead. If such a fallback PPC bank cannot be found either, playback will start without any samples.

This works fine if the `#PCMFile` entry was indeed a "*.P86" one, but there are seemingly no checks in place to make sure that the requested file's extension was actually P86 before going through with the fallback behaviour, meaning it will try to find & replace "P86" in whatever was specified in `#PCMFile`. This results in a SIGSEGV if the originally specified bank is missing & its extension is anything but P86, e.g. PPC or PVI:

```
Thread 1 "pmdplay" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a9887e in __strncpy_avx2 () from <glibc>/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7a9887e in __strncpy_avx2 () from <glibc>/lib/libc.so.6
#1  0x00000000004201ca in strncpy (__len=18446603336221308001, __src=0x7ffffffe4ba0 "", __dest=0x7ffffffd4b30 "GS_PCM.PPC") at <glibc>/include/bits/string_fortified.h:91
#2  FilePath::Strncpy (this=this@entry=0x7fffe6489be0, dest=dest@entry=0x7ffffffd4b30 "GS_PCM.PPC", src=src@entry=0x7ffffffe4ba0 "", size=size@entry=18446603336221308001) at /build/source/src/fmgen/file.cpp:730
#3  0x0000000000420315 in FilePath::Splitpath (this=this@entry=0x7fffe6489be0, path=0x7ffffffe4ba0 "", drive=drive@entry=0x7ffffffd0b30 "", dir=dir@entry=0x7ffffffd4b30 "GS_PCM.PPC", fname=fname@entry=0x7ffffffd8b30 "", ext=ext@entry=0x7ffffffdcb30 "")
    at /build/source/src/fmgen/file.cpp:845
#4  0x0000000000420681 in FilePath::ExchangeExt (this=0x7fffe6489be0, dest=0x7ffffffe4ba0 "", src=<optimized out>, ext=0x42b8b9 ".P86") at /build/source/src/fmgen/file.cpp:968
#5  0x0000000000000000 in ?? ()
```

**Comment by gzaffin** [comment]
I could not split well code changes I made today on this repository for fixing (hopefully) some open issues.
I think commits also fix this SIGSEGV on PPC file name management.
Things are better now.

Can You, OPNA2608, give a feedback about this issue?
Thank You.

**Comment by OPNA2608** [comment]
Sorry for the delay. I briefly tested this and I think this is fixed. Thanks!

**Comment by gzaffin** [comment]
Thank You Christoph!
